#!/usr/bin/env bash
# mkprj

# Generated using mkx 3.0.0: https://github.com/remino/mkx

VERSION='2.1.0'

mkprj_main() {
	trap _exit INT TERM

	E_ARGS=16
	E_EXISTS=17
	E_NOT_DIR=18
	E_CANNOT_MKDIR=19
	E_INVALID_DATE=20

	SCRIPT_INV="$(basename "$0")"
	SCRIPT_PATH="$(readlink -f "$0")"
	SCRIPT_NAME="$(basename "$SCRIPT_PATH")"

	DRY_RUN=0

	while getopts hnt:v OPT; do
		case $OPT in
		h) CMD=help ;;
		n) DRY_RUN=1 ;;
		t) TEMPLATE_NAME="$OPTARG" ;;
		v) CMD=version ;;
		*) _invalid_opt ;;
		esac
	done

	shift "$((OPTIND - 1))"

	[ $# -eq 0 ] && [ -z "$CMD" ] && CMD="help"
	[ -z "$CMD" ] && CMD="process"

	[ -z "$PROJECTS_DIR" ] && PROJECTS_DIR="$(pwd)"
	[ -z "$TEMPLATES_DIR" ] &&
		TEMPLATES_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/mkprj/templates"

	case "$CMD" in
	help | process | version) "mkprj_$CMD" "$@" ;;
	*) _invalid_cmd ;;
	esac

	_exit
}

mkprj_help() {
	cat <<USAGE
$SCRIPT_NAME $VERSION

USAGE: $SCRIPT_INV [<options>] <prjname>

Create a dated project directory.

When <prjname> is not prefixed by a date (in YYYY-MM-DD or YYYYMMDD format),
the current date will be added.

When <prjname> is only a name, it will be created in the PROJECTS_DIR directory,
or if it is not set, in the current directory.

If <prjname> is a path, it will be created in that set path.

OPTIONS:

	-h
		Show this help screen.

	-n
		Dry run. Output path that would be created.

	-t <name>
		Use <name> directory template. Can also be a full path.
		Directory of templates must be set in TEMPLATES_DIR.
		If not set, defaults to the current directory.

	-v
		Show script name and version number.

ENVIRONMENT VARIABLES:

	PROJECTS_DIR
		Directory containing project directories. Default is the current directory.
		Current value: ${PROJECTS_DIR:-.}

	TEMPLATES_DIR
		Directory containing project templates. Default is the current directory.
		Current value: ${TEMPLATES_DIR:-.}

USAGE
}

mkprj_process() {
	prj_name="$1"

	if echo "$prj_name" | grep -q '/'; then
		PROJECTS_DIR="$(dirname "$prj_name")"
		prj_name="$(basename "$prj_name")"
	fi

	if echo "$prj_name" | grep -q -E '^[0-9]{4}-[0-9]{2}-[0-9]{2} '; then
		date="${prj_name:0:4}${prj_name:5:2}${prj_name:8:2}"
		prj_name="${prj_name:11}"
	elif echo "$prj_name" | grep -q -E '^[0-9]{8} '; then
		date="${prj_name:0:8}"
		prj_name="${prj_name:9}"
	else
		date="$(date +"%Y%m%d")"
	fi

	prj_dir="$PROJECTS_DIR/$date $prj_name"

	if [ $DRY_RUN -eq 0 ]; then
		if [ ! -d "$PROJECTS_DIR" ]; then
			[ -e "$PROJECTS_DIR" ] &&
				_fatal "$E_NOT_DIR" "Projects directory is not a directory: $PROJECTS_DIR"

			mkdir -p "$PROJECTS_DIR" ||
				_fatal "$E_CANNOT_MKDIR" "Failed to create projects directory: $PROJECTS_DIR"
		fi

		if [ -e "$prj_dir" ]; then
			_echo "$prj_dir"
			_fatal "$E_EXISTS" "Project directory or file already exists."
		fi

		[ -z "$TEMPLATE_NAME" ] && [ -d "$TEMPLATES_DIR/default" ] && TEMPLATE_NAME=default

		if [ -n "$TEMPLATE_NAME" ]; then
			template_dir="$TEMPLATES_DIR/$TEMPLATE_NAME"

			[ -d "$template_dir" ] || template_dir="$TEMPLATE_NAME"

			[ ! -d "$template_dir" ] &&
				_fatal "$E_NOT_DIR" "Templates directory is not a directory or does not exist: $template_dir"

			cp -r "$template_dir" "$prj_dir" ||
				_fatal "$E_CANNOT_MKDIR" "Failed to create project directory: $prj_dir"
		else
			mkdir -p "$prj_dir" || _fatal "$E_CANNOT_MKDIR" "Failed to create project directory: $prj_dir"
		fi

		if [ -x "$prj_dir/.mkprj/setup" ]; then
			export PROJECT_DIR="$prj_dir"
			export PROJECT_NAME="$prj_name"
			export PROJECT_DATE="$(date -j -f '%Y%m%d' "$date" +"%Y-%m-%d")"
			export PROJECTS_DIR
			export TEMPLATES_DIR

			(
				cd "$prj_dir" || exit "$?"
				.mkprj/setup
			)
		fi
	fi

	_echo "$prj_dir"
}

mkprj_version() {
	_echo "$SCRIPT_NAME $VERSION"
}

_echo() {
	echo "$@"
}

_error() {
	_echo "$@" >&2
}

_exit() {
	exit_code=$?
	exit "$exit_code"
}

_fatal() {
	exit_code="$1"
	shift
	_error "$@"
	exit "$exit_code"
}

_invalid_cmd() {
	_error "Invalid command: $CMD"
	_echo
	mkprj_help
	exit "$E_ARGS"
}

_invalid_opt() {
	_error "Invalid option: $OPT"
	_echo
	mkprj_help
	exit "$E_ARGS"
}

mkprj_main "$@"
